apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: taskflow-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: taskflow-backend
  template:
    metadata:
      labels:
        app: taskflow-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probes.liveness.path }}
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: {{ .Values.backend.probes.liveness.initialDelay }}
            periodSeconds: {{ .Values.backend.probes.liveness.period }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probes.readiness.path }}
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: {{ .Values.backend.probes.readiness.initialDelay }}
            periodSeconds: {{ .Values.backend.probes.readiness.period }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
