apiVersion: v1
kind: Service
metadata:
  name: taskflow-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: taskflow-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
